### PR TITLE
Center circle vertically in the view

### PR DESCRIPTION
**Pull request by nhulongctk35**
emoji-vertically

### CODE REVIEW

**Comment by nhulongctk35** [comment]
Fixed issue #1

**Comment by DimaMukhin** [comment]
awesome thank you!

**Comment by DimaMukhin** [comment]
Sorry, I am going to revert this one, I did not notice that the "emoji string" section is now taking 2 fractions instead of one.

**Comment by DimaMukhin** [comment]
I am going to re-open the issue. You are welcome to continue working on this one. The circle in your image is centered, but the whole text-area section should not get longer. sorry about that

**Comment by nhulongctk35** [comment]
@DimaMukhin Sorry, I open new PR #8  to update new UI following your new requirement. Please take a look

**Pull request merged**
